### ISSUE TITLE
报错：[ts] cannot find module './componets/Hello.vue' 

### ISSUE THREAD

**Issue by CaptainLiao** [githbq/hbq-typescript-vue-boilerplate#1]
如题，在demo.ts上有报错，

浏览器中错误显示如下：
vue.js?e1b2:482 [Vue warn]: Unknown custom element: <hello-component> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

reply:
这个问题是由于你在 ts-loader里 关闭了 transpileOnly 产生的， 应该始终将该选项设置为 true

**Comment by CaptainLiao** [comment]
我曹，居然设置happyPackMode和transpileOnly为true，停止向webpack注入错误，坑爹

误人子弟简直醉了

````
      test: /\.ts?$/,
      exclude: /(node_modules)/,
      use: [
        {
          loader: 'ts-loader',
          options: {
            // happyPackMode: true,
            // transpileOnly: true,
          }
        }
````
reply:
这个问题是我的疏忽 本来想用 awesome-typescript-loader 替代这个 ts-loader 但是发现又有新问题，然后回滚的时候忘了这个问题 
transpileOnly 必须 设置为 true 否则会出问题 比如 上面找不到hello.vue的错误
happyPackMode 多线程编译 ,缺点会忽略掉报错，不再向webpack报错，这个应该设为false
谢谢提醒

**Comment by githbq** [comment]
最新代码 已经默认 注释掉了 happyPackMode:true , 谢谢你的支持
